version: 2
updates:
  # Maintain dependencies for GitHub Actions - Update once every week.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  # Maintain our test dependencies
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Amsterdam"
    # Let core team maintainers review it.
    reviewers:
      - "goalgorilla/maintainers"
    # Prefix all commit messages and include a list of updated dependencies
    commit-message:
      prefix: "Updates: "
      include: "scope"
